### ISSUE TITLE
lesson 1: Error: Cannot find module '.../dist/index.js'

### ISSUE THREAD

**Issue by Vince2301** [FrontendMasters/intro-to-graphql#5]
In lesson 1, I get this error

yarn start
yarn run v1.16.0
$ node dist/index.js
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/Users/vincentleleux/introg/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.

There is indeed no dist folder and the package.json got this line : 
`"start": "node dist/index.js"`

so why is it not throwing an error for you ?

**Comment by rozenteno** [comment]
Hello! What I did was:

- Change the "start" command in package.json to -> `node src/index.js` run with yarn. After that, the folder dist should be created.
- Now change the same line to `node dist/index.js`

To connect to db, make sure you follow these instructions: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/#install-mongodb-community-edition-on-macos if you're on Mac.

I don't know if is the correct way of doing it but it worked for me.
Regards!

**Comment by JhoanLT** [comment]
The dist folder is generated by running the `yarn build` command.

**Comment by Newville23** [comment]
Hey @Vince2301 , You just need to run `yarn build` and then `yarn start` :)

**Comment by erinoggz** [comment]
**Edit nest-cli.json**
```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "entryFile": "your/main/js/path"
}
```
