### ISSUE TITLE
issues with install on windows

### ISSUE THREAD

**Issue by squarewave24** [FrontendMasters/intro-to-graphql#7]
running into following errors while trying to install / run on windows 10 git bash

```
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@12.9.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\dev\usr\intro-to-graphql\node_modules\bcrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user.name\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\dev\\usr\\intro-to-graphql\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\dev\\usr\\intro-to-graphql\\node_modules\\bcrypt\\lib\\binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\dev\usr\intro-to-graphql\node_modules\bcrypt
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\dev\usr\intro-to-graphql\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\usr\intro-to-graphql\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\dev\usr\intro-to-graphql\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\usr\\intro-to-graphql\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\dev\usr\intro-to-graphql\node_modules\bcrypt
node-pre-gyp ERR! node -v v12.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\dev\usr\intro-to-graphql\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\dev\usr\intro-to-graphql\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN intro-to-gql@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user.name\AppData\Roaming\npm-cache\_logs\2019-09-19T13_22_36_326Z-debug.log

user.name@machine-name MINGW64 /c/dev/usr/intro-to-graphql (master)
$ npm build
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?

user.name@machine-name MINGW64 /c/dev/usr/intro-to-graphql (master)
$ npm run build

> intro-to-gql@1.0.0 build C:\dev\usr\intro-to-graphql
> babel src --out-dir dist

Successfully compiled 16 files with Babel.

user.name@machine-name MINGW64 /c/dev/usr/intro-to-graphql (master)
$ npm run dev

> intro-to-gql@1.0.0 dev C:\dev\usr\intro-to-graphql
> nodemon --exec yarn restart

[nodemon] 1.19.2
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 28268 to restart
[nodemon] ignoring: .\.git/**/* node_modules/**/node_modules .\dist/**/*
[nodemon] watching dir(s): src\**\*.js src\**\*.graphql src\**\*.gql
[nodemon] watching extensions: js,json,graphql
[nodemon] starting `yarn restart`
[nodemon] spawning
[nodemon] child pid: 15696
[nodemon] watching 19 files
yarn run v1.17.3
$ rimraf dist && yarn build && yarn start
$ babel src --out-dir dist
Successfully compiled 16 files with Babel.
$ node dist/index.js
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'bcrypt'
Require stack:
- C:\dev\usr\intro-to-graphql\dist\types\user\user.model.js
- C:\dev\usr\intro-to-graphql\dist\utils\auth.js
- C:\dev\usr\intro-to-graphql\dist\server.js
- C:\dev\usr\intro-to-graphql\dist\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\dev\usr\intro-to-graphql\dist\types\user\user.model.js:10:38)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\dev\usr\intro-to-graphql\dist\utils\auth.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\dev\\usr\\intro-to-graphql\\dist\\types\\user\\user.model.js',
    'C:\\dev\\usr\\intro-to-graphql\\dist\\utils\\auth.js',
    'C:\\dev\\usr\\intro-to-graphql\\dist\\server.js',
    'C:\\dev\\usr\\intro-to-graphql\\dist\\index.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Lefthandmedia** [comment]
+1
